accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout, logout_then_login, login
from . import views

urlpatterns = [
	url(r'^registro/', views.Registration.as_view(), name="registro"),
	url(r'^complete-profile/', views.CompleteProfile.as_view(), name="complete-reg"),
	url(r'^profile/$', views.Dashboard.as_view(), name="perfil"),
	url(r'^login/$', login, name="login"),
	url(r'^logout/$', logout, name="logout"),
	url(r'^logout-then-login/$', logout_then_login, name="logout_then_login"),
]

blog2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from posts import urls as UrlsPost
from accounts import urls as UrlsAccounts
from posts.api import urls as UrlsAPI
from main import urls as UrlsMain
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(UrlsMain, namespace="main")),
    url(r'^posts/', include(UrlsPost, namespace="posts")),
    url(r'^accounts/', include(UrlsAccounts)),
    url('', include('social.apps.django_app.urls', namespace="social")),
    url(r'^api/', include(UrlsAPI, namespace="API")),
    url(
    		r'^media/(?P<path>.*)$',
    		serve, 
    		{'document_root':settings.MEDIA_ROOT}
    ),
]

main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.Welcome.as_view(), name="home"),
]

accounts/models.py
from django.db import models
from django.conf import settings

class Profile(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL)
	date_of_birth = models.DateField(blank=True, null=True)
	foto = models.ImageField(upload_to="users/%Y/%m/%d", blank=True)
	avatar = models.ImageField(upload_to="users/%Y/%m/%d", blank=True, null=True)
	bio = models.TextField(blank=True, null=True)
	tel = models.IntegerField(default=000, blank=True, null=True) 

	def __str__(self):
		return 'Perfil del usuario {}'.format(self.user.username)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class UserRegistrationForm(forms.ModelForm):
	password = forms.CharField(label="Contrasena", widget=forms.PasswordInput)
	password2 = forms.CharField(label="Confirma tu contrasena", widget=forms.PasswordInput)

	class Meta():
		model = User
		fields = ('username', 'first_name', 'email')

	def clean_password2(self):
		cd = self.cleaned_data
		if cd['password'] != cd['password2']:
			raise forms.ValidationError('Las contraseñas no coinciden')
		return cd['password2']

class UserEditForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('first_name', 'last_name')

class ProfileEditForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ( 'bio','date_of_birth', 'foto', 'avatar')
		widgets={
			'bio': forms.Textarea(attrs={'class':'materialize-textarea'})
		}

accounts/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from .forms import UserRegistrationForm, ProfileEditForm, UserEditForm
from .models import Profile

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

class Dashboard(View):
	@method_decorator(login_required)
	def get(self, request):
		if request.user.profile:
			template_name = "accounts/perfil.html"
			user_form = UserEditForm(instance=request.user)
			profile_form = ProfileEditForm(instance=request.user.profile)
			context = {
				'user_form':user_form,
				'profile_form':profile_form
			}
			return render(request, template_name, context)
		else:
			profile = Profile()
			profile.user = request.user.save(commit=False)
			profile.save()
			return redirect('profile')
			
	def post(self, request):
		template_name = "accounts/perfil.html"
		
		user_form = UserEditForm(data=request.POST, instance=request.user)
		profile_form = ProfileEditForm(data=request.POST, files=request.FILES, instance=request.user.profile)

		if user_form.is_valid() and profile_form.is_valid():
			user_info = user_form.save(commit=False)
			profile_info = profile_form.save(commit=False)
			user_info.save()
			profile_info.save()
			context = {
				'user_form':user_form,
				'profile_form':profile_form
			}
			return render(request, template_name, context)
		else:
			context = {}
			return render(request, template_name, context)

class Registration(View):
	def get(self, request):
		form = UserRegistrationForm()
		template_name = 'accounts/registration.html'
		context = {
			'form':form
		}
		return render(request, template_name, context)

	def post(self, request):
		new_user_form = UserRegistrationForm(request.POST)
		if new_user_form.is_valid():
			new_user = new_user_form.save(commit=False)
			new_user.set_password(new_user_form.cleaned_data['password'])
			new_user.save()

			perfil = Profile()
			perfil.user = new_user
			perfil.save()

			return redirect('perfil')
		else:
			template_name = 'accounts/registration.html'
			context = {
				'form':new_user_form(request.POST)
			}
			return render(request, template_name, context)

class CompleteProfile(View):
	def get(self, request):
		form = ProfileEditForm()
		template_name = 'accounts/complete-prof.html'
		context = {
			'form':form
		}
		return render(request, template_name,context)
	def post(self, request):
		user = request
		profile_form = ProfileEditForm(data=request.POST, files=request.FILES)
		if profile_form.is_valid():
			profile_form.save()
			return redirect('perfil')
		else:
			template_name = "accounts/complete-prof.html"
			context = {}
			return render(request, template_name, context)

accounts/templates/accounts/complete-prof.html
{%extends 'base.html'%}

{%block content%}
	<form action="." method="POST" enctype="multipart/form-data" class="row top-space">
		{%csrf_token%}
		<div class="input-field col s12">
			<label for="id_bio">Biografía</label>
			{{form.bio}}
		</div>

		<div class="input-field col s12">
			<label for="id_date_of_birth">Año de nacimiento aaaa/mm/dd</label>
			{{form.date_of_birth}}
		</div>

		<div class="input-field top-space col m6 s12">
			<label for="id_foto">Foto de Portada (Larga)</label>
			{{form.foto}}
		</div>

		<div class="input-field top-space col m6 s12">
			<label for="id_avatar">Foto de perfil</label>
			{{form.avatar}}
		</div>

		<input type="submit" value="Cambiar" class="btn top-space col s12 green darken-1">
	</form>
{%endblock content%}

accounts/templates/accounts/perfil.html
{%extends 'base.html'%}
{%load static%}

{%block header%}
	
	<div class="parallax-container">
		<h1 class="title">Bienvenido a tu Dashboard {{request.user.username.title}}</h1>
    <div class="parallax">
    	{%if request.user.profile.foto%}
    		<img src="{{request.user.profile.foto.url}}">
   		{%else%}
   			<img src="{%static 'assets/cover-default.png'%}" alt="">
			{%endif%}
    </div>
  </div>

{%endblock header%}


{%block content%}

	<div class="col s12 m6">
		{%if request.user.profile.avatar%}
		<img src="{{request.user.profile.avatar.url}}" class="avatar" alt="">
		{%else%}
		<img src="{%static 'assets/perfil-default.jpg'%}" class="avatar" alt="">
		{%endif%}
	</div>

	<a href="{%url 'logout'%}" class="btn col s12 m6 red">Cerrar Sesion</a>

	<form action="." method="POST" enctype="multipart/form-data" class="row top-space">
		
		{%csrf_token%}

		<div class="input-field col s6">
			<label for="id_first_name">First Name</label>
			{{user_form.first_name}}
		</div>

		<div class="input-field col s6">
			<label for="id_last_name">Last Name</label>
			{{user_form.last_name}}
		</div>

		<div class="input-field col s12">
			<label for="id_bio">Biografía</label>
			{{profile_form.bio}}
		</div>

		<div class="input-field col s12">
			<label for="id_date_of_birth">Año de nacimiento</label>
			{{profile_form.date_of_birth}}
		</div>

		<div class="input-field top-space col m6 s12">
			<label for="id_foto">Foto de Portada (Larga)</label>
			{{profile_form.foto}}
		</div>

		<div class="input-field top-space col m6 s12">
			<label for="id_avatar">Foto de perfil</label>
			{{profile_form.avatar}}
		</div>

		<input type="submit" value="Cambiar" class="btn top-space col s12 green darken-1">

	</form>

	<div class=" row col s12">
		<h2 class="col s12">Todos tus Posts</h2>

		{%for p in request.user.publicaciones.all%}
			<div class="col s12 m4 item">
				<div class="card grey lighten-4 hoverable">
					<div class="card-image waves-effect waves-block">
						<img src="{{p.imagen.url}}">
						<span class="card-title">
							<a href="{{p.get_absolute_url}}" class="white-text">{{p.titulo}}</a>
						</span>
					</div>
					<div class="card-content">
						<p>Fecha de publicacion:{{p.fecha}}</p>
					</div>
					<div class="card-action">
						<a href="{{p.get_absolute_url}}">Ver Más</a>
					</div>
				</div>
			</div>
		{%endfor%}

	</div>

{%endblock content%}

{%block scripts%}
	
  $(document).ready(function(){
    $('.parallax').parallax();
		//$('label[for="id_avatar"').css({'margin-top':'10px'});
		$('.row').masonry({
		  itemSelector: '.item',
		  columnWidth: '.col',
		  percentPosition: true
		})
  });
{%endblock scripts%}

accounts/templates/accounts/registration.html
{%extends 'base.html'%}

{%block content%}
	<form action="." method="post">
		{%csrf_token%}
		{{form.as_p}}
		<input type="submit" class="button">
	</form>
{%endblock content%}