blog2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from posts import urls as UrlsPost
from accounts import urls as UrlsAccounts
from posts.api import urls as UrlsAPI
from main import urls as UrlsMain
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(UrlsMain, namespace="main")),
    url(r'^posts/', include(UrlsPost, namespace="posts")),
    url(r'^accounts/', include(UrlsAccounts)),
    url('', include('social.apps.django_app.urls', namespace="social")),
    url(r'^api/', include(UrlsAPI, namespace="API")),
    url(
    		r'^media/(?P<path>.*)$',
    		serve, 
    		{'document_root':settings.MEDIA_ROOT}
    ),
]

main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.Welcome.as_view(), name="home"),
]

posts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^nuevo/$', views.Nuevo.as_view(), name="nuevo"),
	url(r'^(?P<slug>[-\w]+)/$', views.DetailView.as_view(), name="detail"),
	url(r'^$', views.ListView.as_view(), name="list"),
	url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.ListView.as_view(), name="list_tag"),
]

templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>
		{%block titulo%}
			EasyClass | Preguntas
		{%endblock titulo%}
	</title>
	<link rel="stylesheet" href="{%static 'css/main.css'%}">
	<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
	<link href="https://fonts.googleapis.com/css?family=Shadows+Into+Light|Bungee+Shade" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
	
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	{%block links%}
	
	{%endblock links%}
	<style>
		
		{%block styles%}
			
		{%endblock styles%}

	</style>
</head>
<body class="grey lighten-2">
	<div class="navbar-fixed">
		<nav>
			<div class="nav-wrapper azul">
				<a href="{%url 'posts:list'%}" class="brand-logo center titulo">EasyClass</a>
				<a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
				<ul class="right hide-on-med-and-down">
					<li><a href="{%url 'main:home'%}">Inicio</a></li>
					<li><a href="{%url 'posts:nuevo'%}">Nuevo</a></li>
					{%if request.user.is_authenticated%}
						<li><a href="{%url 'perfil'%}">Dashboard</a></li>
						<li><a href="{%url 'logout'%}">Cerrar Sesión de {{request.user.username.title}}</a></li>
					{%else%}
						<li><a href="{%url 'login'%}">Iniciar Sesión</a></li>
					{%endif%}
				</ul>
				 <ul class="side-nav" id="mobile-demo">
	        <li><a href="{%url 'posts:list'%}">Todo</a></li>
					<li><a href="{%url 'posts:nuevo'%}">Nuevo</a></li>
					{%if request.user.is_authenticated%}
						<li><a href="{%url 'perfil'%}">Dashboard</a></li>
						<li><a href="{%url 'logout'%}">Cerrar Sesión de {{request.user.username.title}}</a></li>
					{%else%}
						<li><a href="{%url 'login'%}">Iniciar Sesión</a></li>
					{%endif%}
	      </ul>
			</div>
		</nav>
	</div>
	{%block header%}

	{%endblock header%}
	<section class="section row">
		<article class="container white row" style="">
			{%block content%}
				
			{%endblock content%}
		</article>
	</section>
	<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
	<script src="https://unpkg.com/masonry-layout@4.1/dist/masonry.pkgd.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script> 

	<script>
		
		$(".button-collapse").sideNav();
		{%block scripts%}

		{%endblock scripts%}
	</script>

</body>
</html>