blog2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from posts import urls as UrlsPost
from accounts import urls as UrlsAccounts
from posts.api import urls as UrlsAPI
from main import urls as UrlsMain
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(UrlsMain, namespace="main")),
    url(r'^posts/', include(UrlsPost, namespace="posts")),
    url(r'^accounts/', include(UrlsAccounts)),
    url('', include('social.apps.django_app.urls', namespace="social")),
    url(r'^api/', include(UrlsAPI, namespace="API")),
    url(
    		r'^media/(?P<path>.*)$',
    		serve, 
    		{'document_root':settings.MEDIA_ROOT}
    ),
]

main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.Welcome.as_view(), name="home"),
]

posts/api/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^posts/$', views.PostListView.as_view(), name="posts_list"),
	url(r'^posts/(?P<pk>\d+)/$', views.PostDetailView.as_view(), name="posts_detail"),
]

posts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^nuevo/$', views.Nuevo.as_view(), name="nuevo"),
	url(r'^(?P<slug>[-\w]+)/$', views.DetailView.as_view(), name="detail"),
	url(r'^$', views.ListView.as_view(), name="list"),
	url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.ListView.as_view(), name="list_tag"),
]

posts/models.py
from django.shortcuts import reverse
from django.db import models
from django.contrib.auth.models import User

from taggit.managers import TaggableManager

class Post(models.Model):
	""" 
	ESte modelo usa Tags
	"""
	tags = TaggableManager()
	titulo = models.CharField(max_length=140)
	cuerpo = models.TextField()
	fecha = models.DateTimeField(auto_now=True)	
	publicado = models.BooleanField(default=False)
	autor = models.ForeignKey(User, related_name='publicaciones')
	imagen = models.ImageField(upload_to="assets")
	slug = models.SlugField(max_length=280)
	respondido = models.BooleanField(default=False, blank=True)

	class Meta:
		ordering = ('-fecha',)

	def get_absolute_url(self):
		return reverse('posts:detail', args=[self.slug])

	def __str__(self):
		return self.titulo

class Comment(models.Model):
	autor = models.ForeignKey(User, related_name='comentarios')
	post = models.ForeignKey(Post, related_name='comentarios')
	fecha = models.DateTimeField(auto_now=True)
	cuerpo = models.TextField()

	def __str__(self):
		return '{} comento en {}'.format(self.autor, self.post)

	class Meta:
		ordering = ('-fecha',)

posts/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ['titulo','cuerpo','imagen', 'tags']

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['cuerpo']
		widgets={
			'cuerpo': forms.Textarea(attrs={'class':'materialize-textarea'})
		}
		labels={
			'cuerpo':'Ecribe un comentario:'
		}

posts/api/views.py
from rest_framework import generics
from ..models import Post
from .serializers import PostSerializer

class PostListView(generics.ListAPIView):
	queryset = Post.objects.all()
	serializer_class = PostSerializer

class PostDetailView(generics.RetrieveAPIView):
	queryset = Post.objects.all()
	serializer_class = PostSerializer

posts/views.py
# -*- encoding UTF-8 -*-
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View
from .models import Post
from .forms import PostForm, CommentForm
from django.contrib import messages
from django.utils.text import slugify

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from taggit.models import Tag 

from django.db.models import Count


class ListView(View):
	def get(self, request, tag_slug=None):
		template_name = "posts/list.html"
		posts = Post.objects.all()
		tag=None
		if tag_slug:
			tag = get_object_or_404(Tag, slug=tag_slug)
			posts = posts.filter(tags__in=[tag])
		context = {
			'posts':posts,
			'tag':tag
		}
		return render(request, template_name, context)

class DetailView(View):
	def get(self, request, slug):
		template_name = "posts/detail.html"
		post = get_object_or_404(Post, slug=slug)
		comment_form = CommentForm
		post_tags_id = post.tags.values_list('id', flat=True)
		posts_similares = Post.objects.filter(tags__in=post_tags_id).exclude(id=post.id)
		posts_similares = posts_similares.annotate(same_tags=Count('tags'))

		context = {
			'post':post,
			'comment_form':comment_form,
			'posts_similares':posts_similares
		}
		return render(request, template_name, context)

	def post(self, request, slug):
		comment_form = CommentForm(request.POST)
		post = get_object_or_404(Post, slug=slug)
		template_name = "posts/detail.html"
		
		if comment_form.is_valid():
			new_comment = comment_form.save(commit=False)
			new_comment.autor = request.user
			new_comment.post = Post.objects.get(slug=slug)
			new_comment.save()
			context = {
				'post':post,
				'comment_form':comment_form,
			}
			return render(request, template_name, context)
		else:
			context = {}
			return render(request, template_name, context)

class Nuevo(View):
	@method_decorator(login_required)
	def get(self, request):
		template_name = "posts/formulario.html"
		form = PostForm()
		context = {
			'form':form
		}
		return render(request, template_name, context)

	def post(self, request):
		form = PostForm(request.POST, request.FILES)
		if form.is_valid():
			nuevo_post = form.save(commit=False)
			nuevo_post.slug = slugify(nuevo_post.titulo)
			nuevo_post.autor = request.user
			nuevo_post.save()
			#  La docu de Taggit dice esto
			form.save_m2m()
			messages.success(request, 'Tu post a sido guardado con éxito!')
			return redirect('posts:list')
		else:
			messages.error(request, 'No se ha guardado')
			return redirect('posts:nuevo')

posts/templates/posts/detail.html
{%extends 'base.html'%}

{%block styles%}
	.title{
		font-family: 'Bungee Shade', cursive;
	}

	.cuerpo{			
		font-family: 'Shadows Into Light', cursive;
	}
{%endblock styles%}

{%block header%}
<div class="parallax-container">
  <h1 class="title">{{post.titulo}}</h1><div class="parallax"><img src="/media/{{post.imagen}}"></div>
</div>
{%endblock header%}

{%block content%}
	<span>Tags: 
	{% for t in post.tags.all %}
		<div class="chip">{{t.name}}</div>	
	{% endfor %}

	</span>
	<p>Por: <b>{{post.autor}}</b></p>
	<p class="flow-text cuerpo">
		{{post.cuerpo}}
	</p>

	<form action="." method="post">
		<div class="chip">
			<img src="{{request.user.profile.avatar.url}}" alt="">
			{{request.user.username}}
		</div>	
		<div class="input-field">
			{%csrf_token%}
			{{comment_form}}
			<input type="submit" class="btn">
		</div>
	</form>

	<div class="container row col s12">
		<h2>Todos los comentarios:</h2>
		{%for c in post.comentarios.all%}	
			<div class="card grey lighten-2 col s12">
				<div class="card-content">
					<span class="card-title"><div class="chip"><img src="{{c.autor.profile.avatar.url}}"> {{c.autor.username}}<br>{{c.fecha}}</div></span>
					<p>
						{{c.cuerpo}}
					</p>
				</div>
			</div>	
		{%endfor%}
	</div>

	<div class="container row col s12">
		<h3>Tal vez te interesen:</h3>
		{% for p in posts_similares %}
			
			<div class="col s12 m4">
				<div class="card grey lighten-4 hoverable">
					<div class="card-image waves-effect waves-block">
						<img src="{{p.imagen.url}}">
						<span class="card-title title">
							<a href="{{p.get_absolute_url}}" class="white-text">{{p.titulo}}</a>
						</span>
					</div>
					<div class="card-content">
						<p>Fecha de la publicacion: <b> {{p.fecha}} </b> </p>
						<p>Autor de la publicacion: <b> {{p.autor.username}} </b> </p>
					</div>
					<div class="card-action">
						<a href="{{p.get_absolute_url}}">Ver Más</a>
						<a href="#!" class="activator">Ver Tags</a>
					</div>
					<div class="card-reveal">
						<span class="card-title grey-text text-darken-4">Tags<i class="material-icons right">close</i></span>
						{% for t in p.tags.all %}
							<a href="{%url 'posts:list_tag' t.slug%}">{{t.name}}</a>
							{% if not forloop.last %}
								,
							{% endif %}
						{% endfor %}
					</div>
				</div>
			</div>

		{% endfor %}
	</div>
{%endblock content%}

<section class="section">
	<article class="container">

	</article>
</section>

{%block scripts%}
$(document).ready(function(){
  $('.parallax').parallax();
});
{%endblock scripts%}

posts/templates/posts/formulario.html
{%extends 'base.html'%}

{%block content%}

	<form action="." method="POST" enctype="multipart/form-data">
		{%csrf_token%}
		{{form.as_p}}
		<input type="submit" value="¡Postear papu!">

	</form>

{%endblock content%}

posts/templates/posts/list.html
{%extends 'base.html'%}
{%load posts_tags%}

{% block titulo%}
	Inicio
{% endblock titulo%}

<div class="row">
	
</div>

{%block content%}
	{%todos_tags%}
	<h1 class="col s12">Todas las preguntas</h1>
	{% if tag %}
		<h2 class="col s12">Filtrados con tag: {{tag}}</h2>
	{% endif %}

	{%for p in posts%}
		<div class="col s12 item m4">
			<div class="card grey lighten-4 hoverable">
				<div class="card-image waves-effect waves-block">
					<img src="{{p.imagen.url}}">
					<span class="card-title title">
						<a href="{{p.get_absolute_url}}" class="white-text">{{p.titulo}}</a>
					</span>
				</div>
				<div class="card-content">
					<p>Fecha de la publicacion: <b> {{p.fecha}} </b> </p>
					<p>Autor de la publicacion: <b> {{p.autor.username}} </b> </p>
				</div>
				<div class="card-action">
					<a href="{{p.get_absolute_url}}">Ver Más</a>
					<a href="#!" class="activator">Ver Tags</a>
				</div>
				<div class="card-reveal">
					<span class="card-title grey-text text-darken-4">Tags<i class="material-icons right">close</i></span>
					{% for t in p.tags.all %}
						<a href="{%url 'posts:list_tag' t.slug%}">{{t.name}}</a>
						{% if not forloop.last %}
							,
						{% endif %}
					{% endfor %}
				</div>
			</div>
		</div>
	{%empty%}
		<h3>No hay posts</h3>
	{%endfor%}
{%endblock content%}

{%block scripts%}
	$('.row').masonry({
	  // set itemSelector so .grid-sizer is not used in layout
	  itemSelector: '.col',
	  // use element for option
	  columnWidth: '.item',
	  percentPosition: true
	})
{%endblock scripts%}